/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.CustomerDao;
import dao.ExibirDados;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Caang
 */
public class ExibirDadosInterface extends javax.swing.JFrame {

    /**
     * Creates new form ExibirDados
     */
    public ExibirDadosInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeDados = new javax.swing.JTable();
        exibirC = new javax.swing.JButton();
        exibirUsuarios = new javax.swing.JButton();
        exibirAnimais = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaDeDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaDeDados);

        exibirC.setForeground(new java.awt.Color(0, 153, 204));
        exibirC.setText("Dados dos Clientes");
        exibirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirCActionPerformed(evt);
            }
        });

        exibirUsuarios.setForeground(new java.awt.Color(0, 153, 204));
        exibirUsuarios.setText("Dados dos Usuarios");
        exibirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirUsuariosActionPerformed(evt);
            }
        });

        exibirAnimais.setForeground(new java.awt.Color(0, 153, 204));
        exibirAnimais.setText("Dados de Animais");
        exibirAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirAnimaisActionPerformed(evt);
            }
        });

        voltar.setForeground(new java.awt.Color(0, 153, 204));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Exibição de Dados");

        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setText("Dados de Itens");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("© Petshop O Bom Amigo - 2017");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(exibirC, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(exibirUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exibirAnimais, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exibirUsuarios)
                    .addComponent(exibirC)
                    .addComponent(exibirAnimais)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exibirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirCActionPerformed
      ExibirDados exibir = new ExibirDados();
        try {
            tabelaDeDados.setModel(exibir.pegarDadosC());
        }catch(SQLException e){
            System.out.println(e.getMessage());
            System.out.println(e.getMessage());
            DefaultTableModel m = (DefaultTableModel) tabelaDeDados.getModel();
            String[] c = new String[]{"ID", "Nome", "Idade", "Endereço", "Telefone"};
            m.setColumnIdentifiers(c);
            m.setNumRows(0);
            tabelaDeDados.setModel(m);
        }
    }//GEN-LAST:event_exibirCActionPerformed

    private void exibirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirUsuariosActionPerformed
        ExibirDados exibir = new ExibirDados();
        try {
            tabelaDeDados.setModel(exibir.pegarDadosU());
        }catch(SQLException e){
            System.out.println(e.getMessage());
            System.out.println(e.getMessage());
            DefaultTableModel m = (DefaultTableModel) tabelaDeDados.getModel();
            String[] c = new String[]{"ID", "Nome", "Login", "Senha"};
            m.setColumnIdentifiers(c);
            m.setNumRows(0);
            tabelaDeDados.setModel(m);
        }
    }//GEN-LAST:event_exibirUsuariosActionPerformed

    private void exibirAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirAnimaisActionPerformed
        ExibirDados exibir = new ExibirDados();
        try {
            tabelaDeDados.setModel(exibir.pegarDadosA());
        }catch(SQLException e){
            System.out.println(e.getMessage());
            DefaultTableModel m = (DefaultTableModel) tabelaDeDados.getModel();
            String[] c = new String[]{"ID", "Nome", "Raça", "Idade", "Dono", "Tipo"};
            m.setColumnIdentifiers(c);
            m.setNumRows(0);
            tabelaDeDados.setModel(m);
        }
    }//GEN-LAST:event_exibirAnimaisActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
     new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExibirDados exibir = new ExibirDados();
        try {
            tabelaDeDados.setModel(exibir.pegarDadosP());
        }catch(SQLException e){
            System.out.println(e.getMessage());
            DefaultTableModel m = (DefaultTableModel) tabelaDeDados.getModel();
            String[] c = new String[]{"ID", "Nome", "Preço", "Estoque"};
            m.setColumnIdentifiers(c);
            m.setNumRows(0);
            tabelaDeDados.setModel(m);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirDadosInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirDadosInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirDadosInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirDadosInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirDadosInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exibirAnimais;
    private javax.swing.JButton exibirC;
    private javax.swing.JButton exibirUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelaDeDados;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

        public DefaultTableModel pegaModel(){
            return (DefaultTableModel)tabelaDeDados.getModel();
        }
        
        public void modelPadrao(){
            
            
        }

}
